[theme]
base = "light"
primaryColor = "#a50085"
secondaryBackgroundColor = "#e0e0e2"
textColor = "#282a31"

[server]
headless = true

[global]
useContainerWidth = true

[deprecation]
showPyplotGlobalUse = false


[server]
enableCORS = false
enableXsrfProtection = false

